### ISSUE TITLE
Store current window position in persistent memory

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/nog#150]
Perhaps Nog can keep track of the windows it is managing in some persistent memory. That way even if Nog forcefully crashes future Nog instances can attempt to check if windows exist on workspaces that aren't currently being displayed.

By storing the locations of windows in persistent memory you can enable features such as if the user exits work mode and then reenters work mode Nog can try to restore the locations of the currently open windows rather than just switching all windows to unmanaged state.

**Comment by ramirezmike** [comment]
I played around with this a little bit while implementing the tile graph changes. I have a local commit that has serialize/deserialize functions for the grids and for testing I just had it output the serialized tile grid to the log file and whenever it crashed I could copy and paste the string into the config.nog file and it would re-load up all the windows I just had open prior to the crash. It was great for debugging although a little hacky since it was using the log and config file.

Also, it adds a dependency on the serde framework. I mentioned it to @TimUntersberger once before but there may be other options to explore for serializing that save more than just the tile grids?

Whatever the way we serialize, one approach I thought of was having a separate file stored in the appdata folder that has a line dedicated to each possible workspace and then when the user does specific grid-changing events nog could fire off a thread that serializes the ending state of that grid change and stores it on the respective line in the file.

Then if the user switches on/off workmode or nog crashes it could just reload from that file and attempt to put all the windows that still exist in the right place, followed by a "pruning" of the grids to get rid of the windows that are "empty" because maybe the user has shut down apps in the mean time while nog/workmode wasn't running.

I'd think that'd work well but I haven't really prototyped it.

**Comment by TimUntersberger** [comment]
@ramirezmike I mostly agree with you, but would like to have the serialization be extracted away from the implementations, meaning that when implementing some new organizer you won't have to reimplement everything.

> Also, it adds a dependency on the serde framework.

I'd like to avoid that if possible. Especially since the serialization will be very simple format vise.

> but there may be other options to explore for serializing that save more than just the tile grids

I can't think of any other things that would be useful tbh.

> Whatever the way we serialize, one approach I thought of was having a separate file stored in the appdata folder that has a line dedicated to each possible workspace and then when the user does specific grid-changing events nog could fire off a thread that serializes the ending state of that grid change and stores it on the respective line in the file.

Sounds good 👍 We probably will have to reserialize the whole state, as the amount of lines could change, but this shouldn't really be a relevant performance hit.

**Comment by ramirezmike** [comment]
I started working on this and have a WIP pull request #196 where I've implemented the to_string and from_string functions (along with unit tests). I've outlined a todo list I'm planning on working through. 

I added comments for the format but it's simply just storing the nodes in the graph nested in their relationships along with type (tile, column, row), a number indicating the order of display within its parent, a number indicating the size of the node respective to its siblings and either an array of children if the node is a column/row or a windowID if it's a tile. In retrospect, the order could have just been implied by the ordering of children, but it only takes up about a char's worth of space per node and reduces the complexity of the code somewhat to just store it. Here's an example:

>c0|120[t0|60|1,r1|60[t0|40|2,t1|40|3,t2|40|4]]
 
which would represent a grid that looks like the following
   
>11112222   
11113333    
11114444 


I did start looking at the scenario where the user loads up nog after some time or a crash and doing a "prune" operation on what's in the saved-to-disk workspace file and saw this note under the [IsWindow](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-iswindow) function 

> A thread should not use IsWindow for a window that it did not create because the window could be destroyed after this function was called. Further, because window handles are recycled the handle could even point to a different window.

I'm leaning toward the "simple" route that treats any "true" result in the list saved to disk as a valid, _current_ window... Otherwise we could add something that stores the title of the window in the string and maybe do a comparison but... I'm skeptical how often we'll run into false positives vs the extra work/disk space of storing titles that could potentially change as well. Personally, I'd prefer needing to unmanage a window I didn't want managed vs losing a window entirely.

**Comment by ramirezmike** [comment]
I've got this almost done. Right now it tracks all grid modifications across workspaces and when you quit nog and re-launch it re-grabs windows and places them on the workspaces they were on in the layout they were in. It also "prunes" any windows that were closed between nog closing and re-launching.

1. I have the grid saving to a "nog.grid" file in the root nog folder but am open to suggestions.
2. I thought it would need something to "debounce" the read/writes but it seems to be performing well in my initial tests across 10 workspaces and switching between them somewhat rapidly. Maybe it's fine without it?

**Comment by TimUntersberger** [comment]
> I have the grid saving to a "nog.grid" file in the root nog folder but am open to suggestions.

Maybe we could have a concept of something like "snapshots", where a snapshot is just the current layout of the grid. We will provide functionality for saving the current layout as a snapshot and loading it. 

This was just a quick thought I had without thinking about it too much.

> I thought it would need something to "debounce" the read/writes but it seems to be performing well in my initial tests across 10 workspaces and switching between them somewhat rapidly. Maybe it's fine without it?

Probably shouldn't matter, because you won't update the grid multiple times a second, right?

**Comment by ramirezmike** [comment]
>Maybe we could have a concept of something like "snapshots", where a snapshot is just the current layout of the grid. We will provide functionality for saving the current layout as a snapshot and loading it.

Yeah, as I was playing around with it I had a similar thought of like.. adding a line in the workspace config that is the grid layout you want and then nog can automatically launch and place those. But, also separately like you're saying it'd be cool to save a layout and load it. I do feel like either of these would be separate issues but both would be pretty useful.

>Probably shouldn't matter, because you won't update the grid multiple times a second, right?

Yeah, the only scenario I can think of is resizing because that's something that is also stored in the layouts, but.. yeah so far in my testing it seems to handle it ok. 

I set it up to also work when turning work mode on/off. Hoping to have this in a "done" state either today or tomorrow, it works pretty well and is kinda neat.

**Comment by ramirezmike** [comment]
I'll probably merge the pull request I have for this either today or tomorrow. It's storing the grid in a file called "grid.nog" but it's not exactly a _nog_ filetype that matches the configs so I'm still debating changing it to something like layout.grid or nog.grid.

I'll create new issues for the other features of setting up something that can save/load layouts in the configs.

**Comment by ramirezmike** [comment]
@keepitsane check out the latest development release and let me know if that's behaving like you expected. It should work across launches of nog and toggling workmode.

**Comment by keepitsane** [comment]
@ramirezmike I haven't gotten a chance to do a more comprehensive testing, but just trying with one window seems to be breaking things. 

I launched nog fresh and opened one firefox window and focused it on workspace 1. I then toggled work mode off and then back on and my firefox window had completely disappeared. After toggle work mode on and off a few times my browser window would show up assigned to a random workspace seemed to get pushed to workspace 10 a few times and workspace 2 a few times as well. It would only reappear assigned to these workspaces randomly so I had to toggle work mode on and off a bunch of times to get my window back. I'll keep testing this build for today and report back if I can what may be the cause of this issue.

**Comment by keepitsane** [comment]
Yeah after a bit more testing seems like it is not working properly at all. Maybe it is not taking into consideration multi monitor setups or if a workspace is preassigned to a specific monitor using the config file? 

Not really sure just spitballing potential ideas, it either loses all the windows into oblivion and even exiting Nog completely doesn't seem to bring them back to where even Windows can find them or it just randomly moves then around to different workspaces.

Here is my workspace.grid file
```
t0|120|3411586



t0|120|5178810
t0|120|9635740


t0|120|1314006

```

I currently have the following windows open and workspaces assigned to each monitor:
Monitor 3
- Workspace 4 - Empty
- Workspace 5 - 1 Firefox window
- Workspace 6 - Spotify

Monitor 2 - Primary
- Workspace 1 - 1 Firefox window
- Workspace 2 - Empty
- Workspace 3 - Empty

Monitor 1
- Workspace 7 - Empty
- Workspace 8 - Empty
- Workspace 9 - Discord

Workspace 10 is not assigned to any specific monitor in my config file.

Also my log file has a bunch of these errors. Which to be honest I am not sure if it is an error or not because of the error message 😄 
```
[2020-12-02 11:08:35.357846 -05:00] ERROR [src\main.rs:496] Init(Null)
[2020-12-02 11:08:35.358348 -05:00] ERROR [src\system\win\api.rs:53] WINAPI ERROR: The operation completed successfully.
```

**Comment by ramirezmike** [comment]
Ah, I see what you're talking about. I mainly use nog on two monitors and it's been working well for me but I think it's because I only keep my last workspace on my 2nd monitor and the rest on the first monitor. Once I started adding more and changing the order I started running into what you're seeing. It's like it's cycling the workspaces for me. 

This shouldn't be too crazy to fix, I'll see if I can fix that tonight. Sorry about that but thanks for the feedback!

And I've seen that WINAPI error for a bit now, I'm not 100% sure what's causing it to appear but I don't see any strange behaviors associated with it.

**Comment by ramirezmike** [comment]
Ok @keepitsane I updated the code and created a pullrequest [here](https://github.com/TimUntersberger/nog/pull/199) from my fork. The actions are setup so it built an exe on my branch [here]()

**Comment by keepitsane** [comment]
@ramirezmike So it seems like windows are being restored to the current workspaces now. However, workspaces on my secondary monitors do not redraw the last active workspace. What I mean by this is if I have workspace 6 on my secondary monitor with a window focused when I toggle between work mode until I revisit workspace 6 it does not show the window that was there.

I think you may also need to store the data of which workspaces where being displayed when work mode is toggled off or Nog is exited. Cause even when toggling work mode if auto focuses on workspace 1 rather than the last workspaces I was focused on. I think this should be the behavior when launch Nog from a fresh start, but toggling work mode should bring you back to the last workspace you had displayed.

Let me know if that makes sense and if not I can try to do a better job at explaining what I mean. Other than that one issue it seems to be working much better then before!

**Comment by ramirezmike** [comment]
Thanks for the feedback. I made some changed on top of that branch that re-focus the workspaces that were focused on each display and tested it out on my two monitors and it re-shows the workspaces that were focused across toggling of workmode.

I went ahead and merged it into development since it + the other fix resolves the issues you pointed out above. Let me know what you think of how it works and if you'd like it to behave differently.

**Comment by keepitsane** [comment]
Yep seems like everything is working as expected now. The only bug that still remains is the border around Firefox and Chrome like you said I believe. I think once that gets fixed it should be safe to close this issue. 

Great work really makes using Nog much more seamless for me now!

**Comment by ramirezmike** [comment]
Awesome, good to hear that's working better!

As far as the border goes... I think there's an aspect of this that behaves differently on different computers/resolutions. First of all, I initially had my configs setup like the following



    rule ".*- Mozilla Firefox|Mozilla Firefox" #{
        has_custom_titlebar: true,
        firefox: true,
    };

which looked like this

![Screenshot from 2020-12-04 19-51-02](https://user-images.githubusercontent.com/1421719/101228561-36472e80-366a-11eb-9030-c6c729a8b05a.png)


but I also tested with just "firefox.exe" and also with the rule commented out and it looked the same. And when I debug I can definitely see that nog hits the rules and everything.

Chrome behaves slightly differently

No rules:

![Screenshot from 2020-12-04 20-04-53](https://user-images.githubusercontent.com/1421719/101228990-1dd81380-366c-11eb-86d7-df8fb3520620.png)

With the rules 

    has_custom_titlebar: true,
    chromium: true,

![Screenshot from 2020-12-04 20-07-47](https://user-images.githubusercontent.com/1421719/101229073-81624100-366c-11eb-9f6d-fcda66000367.png)

Which is like... the browser is too high up and the tab is cut off by the nog app bar.

So, there's code in src/renderer/win.rs that uses GetSystemMetricsForDpi which was I think to fix #92. When I look at the output of it, I get 0 for everything [which indicates it failed](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetricsfordpi), so when I change those calls to fall back on GetSystemMetrics in the case of 0 it looks like this:

![Screenshot from 2020-12-04 20-26-59](https://user-images.githubusercontent.com/1421719/101229619-1ebe7480-366f-11eb-98d9-fe20831cda3e.png)

and firefox:

![Screenshot from 2020-12-04 20-28-08](https://user-images.githubusercontent.com/1421719/101229641-40b7f700-366f-11eb-8ff6-97c9a78e1d5b.png)

which is sooo close but it's slightly off on the Top value and it's different between firefox and chrome. @TimUntersberger do you have any ideas? I could add chrome-specific and firefox-specific offsets but I worry that won't be the same for everyone.

**Comment by ramirezmike** [comment]
I played around with adding rule-configurable offsets for each program but even when I could get it configured right, the offsets were different between my main monitor and my laptop monitor.

I don't think this is related to storing the grid in persistent memory. Perhaps it should be a new issue?

**Comment by keepitsane** [comment]
I think I potential found the root of this issue. Are you sure the custom rules are being mached when windows are restored?

When I toggle work mode or restart Nog and a firefox window is restored in the log file I never see a `Rule(^firefox.exe$) matched!`

For example here:
```
[2020-12-09 18:50:53.970427 -05:00] INFO [src\tile_grid.rs:63] Beginning Rendering
[2020-12-09 18:50:53.970427 -05:00] INFO [src\tile_grid.rs:79] Rendering completed
[2020-12-09 18:50:53.970427 -05:00] INFO [src\tile_grid\store.rs:22] Saving 1 
[2020-12-09 18:50:54.260725 -05:00] INFO [src\event_handler\keybinding.rs:36] Received keybinding of type ChangeWorkspace(5)
[2020-12-09 18:50:54.260725 -05:00] DEBUG [src\tile_grid.rs:48] IsFullScreened? false FocusedNode: Some(0)
[2020-12-09 18:50:54.261721 -05:00] DEBUG [src\tile_grid.rs:50] 
████████████████████████████████████████████████████████████████
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
█AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA█
████████████████████████████████████████████████████████████████
A ~ NodeID:0 WinID:2688600 - Store current window position in persistent memory · Issue #150 · TimUntersberger/nog  Firefox Developer Edition Size: 120 Order: 0
```

Seems like it restores the window, but never checks the config file to see if any rules exist. Since Nog only matches rules when a new window is first opened. When restoring existing windows the Show event is never triggered and therefore Nog never runs the windows through the rules in the config file.

This is how it is done for the toggle floating mode keybind:
```
state
     .event_channl
     .sender
     .clone()
     .send(Event::WinEvent(WinEvent {
           typ: WinEventType::Show(true),
           window,
     }))
     .expect("Failed to send WinEvent");
```

**Comment by ramirezmike** [comment]
>Are you sure the custom rules are being mached when windows are restored?

Ok, I see what you mean. That's definitely part of this, I'll work on that.

Are you seeing the browsers not lining up vertically like in the images I showed above? I think _that_ aspect of it might be a separate issue.

**Comment by keepitsane** [comment]
> Are you seeing the browsers not lining up vertically like in the images I showed above? I think _that_ aspect of it might be a separate issue.

Yeah seems like the higher the monitor resolution the bigger the gap between the appbar and the window becomes.



This monitor 1 at `3440 * 1440`
![image](https://user-images.githubusercontent.com/13246774/101713496-bfdd6e80-3a65-11eb-8fa1-f0b8031a48ad.png)

This monitor 2 at `1920 * 1080`
![image](https://user-images.githubusercontent.com/13246774/101713486-b9e78d80-3a65-11eb-9b8f-a0465f1ba650.png)

This monitor 3 at `2560 * 1440`
![image](https://user-images.githubusercontent.com/13246774/101713504-c370f580-3a65-11eb-9d52-268233dc7799.png)

If I take monitor 3 and lower the resolution to `1920 * 1080` the gap goes away complete.
![image](https://user-images.githubusercontent.com/13246774/101713850-78a3ad80-3a66-11eb-8499-7772febcf168.png)

So like you said this seems like some kind of resolution scaling issue.

**Comment by ramirezmike** [comment]
That's a good observation. I did notice I was only getting a gap on the top for chrome, but with firefox there was a gap on all sides. Are you noticing a gap anywhere else aside from the top and, if so, does it also change with resolution?

Also, separately, are you using this build regularly and have you noticed anything else that should be addressed?

**Comment by keepitsane** [comment]
When using firefox I only get a gap on the top most edge below the appbar when the resolution is about `1920*1080`. For the left, right, and bottom edge I see no gap at all at any resolution. 

When testing out the chromium version of Microsoft Edge, with the chromium rule set in my config. I see no gap at all on both monitor 1 (`3440 * 1440`) and monitor 2 (`1920 * 1080`), but a slight gap at the top on monitor 3 (`2560 * 1440`). 

Left is Firefox and right is Edge
![image](https://user-images.githubusercontent.com/13246774/101715756-01701880-3a6a-11eb-8513-ed87306ae836.png)

Adjust monitor 3 to `1920 * 1080` fixes it for both
![image](https://user-images.githubusercontent.com/13246774/101715890-46944a80-3a6a-11eb-8ec4-5cb8c2b92712.png)

Regardless of the browser and resolution I only see a gap at the top, never on the sides or bottom.

**Comment by ramirezmike** [comment]
Hey @keepitsane 

I made a branch [here](https://github.com/TimUntersberger/nog/releases/tag/work-mode-toggle-fix-release) that has a fix for the issue of windows appearing incorrectly after toggling work mode on and off repeatedly.

In my testing this made nog behave more consistent when showing windows across launches and toggling work mode on and off. If you get a chance can you test that out and let me know if that works like you'd expect?

This does not resolve the border issues in chrome and firefox, which I think is a separate issue. I'm tackling that separately and have gotten chrome to the point that it works but firefox still behaves strangely. I noticed that when you make it really small it just stops using the settings all together. 

But yeah, let me know how that branch's release works and we can hopefully get that merged and then work on the browser size differences.

**Comment by keepitsane** [comment]
Let build seems to fix have fixed this issue! I can close this issue once the branch has been merged in.

I will move the comments about the gap to its own separate issue.

**Comment by keepitsane** [comment]
Looks like this branch seemed to have introduced a new issue, opening new windows of any application doesn't seem to automatically focus it on the currently active workspace.

Even for applications that have rule to focus it on a specific workspace in the config file, just opens up and never gets focused. 

@ramirezmike This bug happens both when starting Nog from fresh or toggling work mode. I have to manual focus the window using my keybinding.

Not sure if I should open a separate issue, but let me know if you would like me to.

**Comment by ramirezmike** [comment]
Nah, I can address it on this branch since this commit caused it. Thanks for the quick feedback, I'll check it out.

**Comment by ramirezmike** [comment]
ok @keepitsane, I pushed a fix for the focusing issue [here](https://github.com/TimUntersberger/nog/releases/tag/work-mode-toggle-fix-release). 

I had re-ordered when the windows get initialized until after nog determines they should get managed so that there aren't any modifications to the window unless nog is definitely going to manage the window, but part of the detection depended on the windows getting initialized first, so I updated that function to look at the current style. Let me know if that works for you.

**Comment by keepitsane** [comment]
@ramirezmike This fixes the issue. Thanks for the quick fix!

**Comment by keepitsane** [comment]
@ramirezmike Been continuing testing of this build and feels fairly stable. I think you should be safe to merge into the development branch.

**Comment by ramirezmike** [comment]
Good to hear! Thanks for testing it out and catching those issues. I might wait another day or so just in case Tim wants to check out the code changes, but yeah, I'm definitely using this feature really heavily; thanks for suggesting it!

**Comment by ramirezmike** [comment]
Closing this issue for now as a fix has been merged into the custom-language branch.
