### ISSUE TITLE
Clock is no longer updating

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/nog#155]
The clock in the appbar doesn't seem to work on the latest build anymore. It only updates the clock when switching to a different workspace.

**Comment by ramirezmike** [comment]
hah, I was just late to a meeting because of this.

It looks like the code to start a thread that updates every 200ms was commented out [here](https://github.com/TimUntersberger/nog/blob/development/src/bar/create.rs#L19).

I'm not sure why though. If you uncomment it and re-add the usings it seems to work again. I suspect @TimUntersberger will have more answers why it's currently commented out; it's possible that it causes another issue in the development branch that I'm unaware of and it made more sense to temporarily disable it.

**Comment by TimUntersberger** [comment]
Well shit. I Probably forgot to uncomment it haha.

**Comment by TimUntersberger** [comment]
Newest commit should fix this.
