### ISSUE TITLE
[Feature Request] Split mode component

### ISSUE THREAD

**Issue by takase1121** [TimUntersberger/nog#166]
This is really just a feature request, I wish to have a component to show if nog is splitting horizontally or vertically. That would greatly help.

**Comment by ramirezmike** [comment]
I have a version that is part of a WIP pull request that can be seen [here](https://github.com/TimUntersberger/nog/pull/164/files#diff-dfbfe886716555c288c28dd82e09c23d). It's not compatible with the current nog branches but conceptually it's the same thing: it indicates what split mode you're in.

![indicator](https://user-images.githubusercontent.com/1421719/94878161-9df2ba80-042a-11eb-9330-fb82cf5fae73.png)


Two things to note:

1. I implemented the component to show vertical/horizontal/fullscreen. I mostly did it for the fullscreen indicator because I actually confused myself enough times that I thought it would be nice to show. So, when a window is fullscreened it shows the fullscreen icon (because splits aren't really important when you're fullscreened) and otherwise it shows the current split mode. My vote would be to have something like that.

2. I had hardcoded it to emojis 🔳, ↔️, ↕️ but I suspect it should be something that people would want configurable? Little technical, but not sure if it's worth adding another spot where the bar is locking the config to see what the configured values are; maybe it should be something that is just cached in the component and refreshed on hotreload?

**Comment by TimUntersberger** [comment]
This issue actually shows a different problem. We should probably expose some metadata to the user in the config files, so they could create such components themselves or even using popups.

**Comment by takase1121** [comment]
> This issue actually shows a different problem too. We should probably expose some metadata to the user in the config files, so they could create such components themselves or even using popups.

Yes. Actually, I think there should be an API where user can control nogs, like the onclick function of a component can be used to launch something, show/hide Windows, switch workspace, etc.

**Comment by TimUntersberger** [comment]
@takase1121 

I currently have two functions implemented:

* `nog_get_split_direction`
* `nog_do`

## nog_get_split_direction

Returns the split direction of the focused window.

Possible values:

* `Horizontal`
* `Vertical`
* empty string

## nog_do

Basically simulates a keybinding activation.

usage
```nog
no_do(change_workspace(10));
```

Can you list all of the things you need included in the core lib?

**Comment by takase1121** [comment]
maybe
- get the state of window (hidden/unmanaged),

I dunno, maybe some other people could think of more things to add

**Comment by ramirezmike** [comment]
- show whether a workspace is fullscreened or not

I'm actually struggling to think of other things.. like, maybe config settings like your current gaps? I don't know how useful that'd be.

**Comment by TimUntersberger** [comment]
@takase1121 the newest release now contains a [split_direction](https://timuntersberger.github.io/nog/#/configuration/bar?id=split-direction) component that does what you want.
