### ISSUE TITLE
Clicking on workspace number in appbar is broken

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/nog#238]
**Version (which release did you use?)**
Developement cd1178a

**Describe the bug**

Previous version allowed to use the mouse to click on the workspace number in the appbar to quickly switch over to that workspace. In the current version clicking on the workspace number does nothing.

**Comment by TimUntersberger** [comment]
This works for me. Are you always encountering this issue or is there some pattern?

**Comment by ramirezmike** [comment]
I've been running that deadlock branch and this also doesn't work for me. I get this in the log whenever I click

>[2021-02-19 08:28:28.314668 -05:00] ERROR [twm/src/main.rs:952] Expected type RustValue, but found Number

I'm not using custom workspace titles, just letting nog label the workspaces with numbers. I'm not sure if that's part of it?

**Comment by keepitsane** [comment]
Can confirm that this functionality is broken for me in both the development and deadlock branches, as I just double checked to be 100% sure.

**Comment by keepitsane** [comment]
Can confirm this bug is still persistent in the latest 0.13 build.

**Comment by TimUntersberger** [comment]
Hmmm.... I can't reproduce this.

**Comment by TimUntersberger** [comment]
> I'm not using custom workspace titles, just letting nog label the workspaces with numbers. I'm not sure if that's part of it?

I disabled my workspace customization and it still works for me.

**Comment by keepitsane** [comment]
I tried disabling my workspace customization and it started working for me. Maybe I have workspace configured incorrectly somehow?

In my `config.ns` I have the follow:
```
import workspace

// Including my appbar configure just in case I am missing something here
nog.bar.configure(#{
    font: "FiraCode NF",
    font_size: 17,
    color: 0x4B326E, 
    components: #{
        left: [nog.bar.components.workspaces()],
        center: [nog.bar.components.time("%l:%M:%S %p")],
        right: [nog.bar.components.active_mode(), nog.bar.components.padding(5), nog.bar.components.date("%a, %e %b %Y"), nog.bar.components.padding(1)]
    }
})
```

and in my `workspace.ns` i have the follow:
```
import nog

export fn init() {
    nog.workspace.configure(1, #{
        monitor: 2
    })

    nog.workspace.configure(2, #{
        monitor: 2
    })

    nog.workspace.configure(3, #{
        monitor: 2
    })

    nog.workspace.configure(4, #{
        monitor: 3
    })

    nog.workspace.configure(5, #{
        monitor: 3
    })

    nog.workspace.configure(6, #{
        text: " 阮 ",
        monitor: 3
    })

    nog.workspace.configure(7, #{
        monitor: 1
    })

    nog.workspace.configure(8, #{
        monitor: 1
    })

    nog.workspace.configure(9, #{
        text: " ﭮ ",
        monitor: 1
    })

    nog.workspace.configure(0, #{
        monitor: 2
    })
}
```

**Comment by keepitsane** [comment]
When I have workspace customization I am getting the same error as @ramirezmike in my log file
`[2021-02-23 15:31:31.288129 -05:00] ERROR [twm\src\main.rs:939] Expected type RustValue, but found Number`

**Comment by TimUntersberger** [comment]
@keepitsane I copied your workspace configuration and still can't reproduce this.

**Comment by keepitsane** [comment]
Huh that is very odd not sure what the issue is then. @ramirezmike are you by any chance still experiencing this issue?

**Comment by ramirezmike** [comment]
Yes, I was looking at this last night. I'll look more tonight maybe. I did find a couple interesting things; I'll add later.

**Comment by ramirezmike** [comment]
Ok, so, this'll be a little technical but... for starters I'm on current release, I'm not using any custom workspace configurations and I am just launching nog, managing apps on a few workspaces and then trying to click on the workspace number.

I get this error

> ERROR [twm/src/main.rs:939] Expected type RustValue, but found Number

Which I tracked down to being caused by [this](https://github.com/TimUntersberger/nog/blob/48124c0979ede7797da801519bf6d3470d1a3851/twm/src/bar/component.rs#L187) not matching up with the arguments. It should be [0] is displayID, [1] is value and [2] is index like you can see [here](https://github.com/TimUntersberger/nog/blob/48124c0979ede7797da801519bf6d3470d1a3851/twm/src/bar/component.rs#L209) and a few other places where this stuff is connected. 

So, I changed that to this

```
                    let value = rust_value!(&args[1])?.clone();
                    let idx = *number!(&args[2])?;
                    let display_id = state.lock().get_current_display().id;
```

and it "fixes" that specific issue. (I had a hunch about the display_id but it ended up not changing anything BUT maybe it makes sense to use args[0] to get the display_id rather than locking the state?)
 
BUT this causes a panic later on when it's trying to convert value to an i32. This is really interesting to me because the rust_value! macro was complaining before about getting a number... and I _think_ it was doing that because DisplayId (the first argument) is basically a number... but it's happy with the 2nd argument (args[1]) which... _should_ be an **Arc<Box<dyn Any + Send + Sync>>** where the Any is an i32 for the grid_id as seen [here](https://github.com/TimUntersberger/nog/blob/48124c0979ede7797da801519bf6d3470d1a3851/twm/src/bar/component/workspaces.rs#L46) which gets set [here](https://github.com/TimUntersberger/nog/blob/48124c0979ede7797da801519bf6d3470d1a3851/twm/src/bar/component.rs#L39) and gets passed into that dynamic function [here](https://github.com/TimUntersberger/nog/blob/48124c0979ede7797da801519bf6d3470d1a3851/twm/src/bar/create.rs#L215). 

but it panics on this [line](https://github.com/TimUntersberger/nog/blob/48124c0979ede7797da801519bf6d3470d1a3851/twm/src/bar/component/workspaces.rs#L55) 

```
       let id = *value.downcast_ref::<i32>().unwrap();
```

because the dereferenced value isn't an i32, I guess? I can't figure out what it is, but I'm really curious what's going on here because as far as I can tell this _should_ be an i32. I tried dereferencing further and comparing type_id() results with TypeId::of::<i32>() calls (as well as wrapped with Arc and Box) and nothing matches up to what I expect and TypeId is somewhat difficult to "reverse engineer" for anything that isn't pretty simple. 

That's where I am right now. I personally never use this feature but, again, I'm super curious what exactly is going on. Going to to keep looking..

**Comment by TimUntersberger** [comment]
@ramirezmike the weirdest part about this whole stuff is why am I not experiencing this 😆? This seems really weird.

**Comment by keepitsane** [comment]
@TimUntersberger would you mind posting how you have your appbar configured in you config file? I commented out my nog.bar.configure in my `config.ns` and it started working. So I am guess it is something to do with how @ramirezmike and myself have our appbars setup.

Here is my appbar configure once more for quick reference:
```
nog.bar.configure(#{
    font: "FiraCode NF",
    font_size: 17,
    color: 0x4B326E, 
    components: #{
        left: [nog.bar.components.workspaces()],
        center: [nog.bar.components.time("%l:%M:%S %p")],
        right: [nog.bar.components.active_mode(), nog.bar.components.padding(5), nog.bar.components.date("%a, %e %b %Y"), nog.bar.components.padding(1)]
    }
})
```

**Comment by keepitsane** [comment]
Further testing it seem to be an issue with how I have my components setup. Removing that section only fixes the issue.

**Comment by keepitsane** [comment]
Even more specifically removing this line fixes it, so I believe this must be the root cause of the problem:
`left: [nog.bar.components.workspaces()],,`

**Comment by TimUntersberger** [comment]
This is my bar configuration:

```nogscript
nog.bar.configure({
  font: "CaskaydiaCove NF",
  font_size: 18
})
```

The problem is 100% the conversion between the rust object and nogscript representation.

**Comment by ramirezmike** [comment]
Just confirming that I too have this in my config

>left: [nog.bar.components.workspaces()],

Since I want the workspaces on the left, it's fine for me to remove it to get this to work as a workaround. But.. yeah, it does seem like a rust and nogscript conversion issue..

Not sure if this is helpful but I think the type of the RustValue macro is this

>alloc::sync::Arc<alloc::boxed::Box<dyn core::any::Any+core::marker::Send+core::marker::Sync>>

which does evaluate to being equal to this with Type_Id..

>std::sync::Arc<Box<dyn core::any::Any+core::marker::Send+core::marker::Sync>>

But... I can't get an i32 out of it with all the attempts of different layers of dereferencing and Any downcasting that I tried. It just starts returning really different Type_Ids and I'm not sure what they are..

**Comment by TimUntersberger** [comment]
Should be fixed in latest development release.

**Comment by keepitsane** [comment]
Hmm seems like a new development build hasn't been released yet?

**Comment by TimUntersberger** [comment]
Accidently pushed a build that doesn't compile. Now there should be a new release.

**Comment by keepitsane** [comment]
I am sorry am I missing something? The last development build I see is still from 5 days ago.

**Comment by TimUntersberger** [comment]
Looks like renaming the excutable fails, because the previous release folder is still there. I now rm the renamed executable before renaming the new one.

**Comment by keepitsane** [comment]
I have now been able to test `nog.bar.components.workspaces()` and it is working as expected. Thank you!
