### ISSUE TITLE
Default binding not working

### ISSUE THREAD

**Issue by svcop3** [TimUntersberger/nog#240]
**Version (which release did you use?)**
V0.12.0

**Describe the bug**
Key bindings don't seem to work, eg alt+x does not quit. It seems to be processed by the active window. Is the window manager supposed to intercept it? 
When run the first time there is no config file so I added one with bind "Alt+X" quit(). Still doesn't work. I feel like I am missing something obvious. 
Also tried building from master and still didn't work either

**To Reproduce**
Run the exe
Press alt+x
Nothing happens

**Expected behavior**
Alt+x should quit

**Actual behavior**
Doesn't quit, keypress is processed by active window

**Comment by ramirezmike** [comment]
Let's check a few things and if you are missing something we can try to make that more obvious too since things should work somewhat out of the box.

1) where are you putting the config file? It should be in your user's appdata roaming folder like for me it's "C:\Users\ramirezmike\AppData\Roaming\nog

(I noticed the documentation says %APPDATA%/nog so we might need to update that)

2) what's in your config file?

3) a log folder should exist in that nog folder and there may be a couple files in it depending on how many times you ran it. Could you post what's in your current log (that'd be whatever happened during your last run of nog)

4) does nog's app bar appear and does it look like it's running (like is the time ticking on the clock)?

Additionally, if you can still see your windows taskbar you should be able to quit out of nog using the system tray icon. Let me know if that also doesn't work for you.

**Comment by svcop3** [comment]
[twm_r2021-02-14_05-54-48.log](https://github.com/TimUntersberger/nog/files/5976646/twm_r2021-02-14_05-54-48.log)
[twm_rCURRENT.log](https://github.com/TimUntersberger/nog/files/5976647/twm_rCURRENT.log)
1/2 Config file is in roaming/nog. Actually the stable version 0.12.0 is in roaming/wwm, but I'll discuss the development release from now on, if that's OK, which is in roaming/nog. I am using the twm.exe precompiled from the development release. 
So a blank config.ns is created in roaming/nog on the first run of twm.exe. I can open the config.ns in notepad and add "nog.bind("F1", () => print("Hello World")). When I save, a window pops up and tells me "Class Null doesn't have operator . implemented"
4. The nog bar appears and the clock is working. The program appears to be functioning : when I open a new window, it positions it within the grid. 
The task bar disappears, but I can stop the twm process from pwsh

**Comment by ramirezmike** [comment]
ah, I suspect from this error

>Class Null doesn't have operator . implemented

that you're missing this at the top of your config file

>import nog

and it's crashing on the nog object not existing. That might not be clear in the documentation; we used to have an example but we're still catching up with the documentation after changing the config structure. You can find an example config file [here](https://github.com/TimUntersberger/nog/blob/master/example/config.ns). Let me know if that's the problem.

**Comment by svcop3** [comment]
Yes that was the problem. I had to copy everything in the example folder. Thanks

**Comment by ramirezmike** [comment]
@TimUntersberger we might want to update the docs, it currently says the configs are in %AppData%/nog and not %AppData%/roaming/nog

**Comment by TimUntersberger** [comment]
@ramirezmike `%APPDATA%` expands to `C:\Users\<USER>\AppData\Roaming` for me.

**Comment by ramirezmike** [comment]
ah whoops nevermind
