### ISSUE TITLE
support not following moved window in window.move_to_workspace()

### ISSUE THREAD

**Issue by garymm** [TimUntersberger/nog#263]
Currently if I move a window to workspace N, the focus follows that window to that workspace.
I'd like to be able to remain on my current workspace rather than follow the window.

Perhaps an optional boolean argument to `window.move_to_workspace()`?

**Comment by ramirezmike** [comment]
this is like the distinction between carrying or moving. Right now, in nog we use the word "move" somewhat more like "carry." I don't think we should rename everything so maybe instead it could be a separate function like "window.send_to_workspace()"

that said, @TimUntersberger  is currently making some changes to the config system and after that's done we'll be able to expose more functionality in the nog API to the config files which would open up the possibility of writing something like this right into a keybinding rather than needing to make big changes in the code base. 

Getting this implemented would be great though so I think leaving this issue open to track this is good and we can use it as an example of what kind of API functions we'll need to expose.

**Comment by TimUntersberger** [comment]
> I don't think we should rename everything so maybe instead it could be a separate function like "window.send_to_workspace()"

Supporting an optional boolean argument for the function like he proposed should be fine imo.

**Comment by ramirezmike** [comment]
>Supporting an optional boolean argument for the function like he proposed should be fine imo.

yeah, that's fair. Might be good to address after #259

**Comment by TimUntersberger** [comment]
After #259 is merged this function won't focus the workspace. To replicate the old behaviour you will have to move the window and then manually focus the workspace. Closing this for now, because the PR will be merged soon.
