### ISSUE TITLE
Close telegram window do not affect workspace layout

### ISSUE THREAD

**Issue by TTTPOB** [TimUntersberger/nog#288]
**Version (which release did you use?)**

**Describe the bug**

Close [telegram](https://telegram.org/)  window do not affect workspace layout
**To Reproduce**

1. create a workspace
2. open `telegram` and another window (b)
3. they should be side by side
4. close `telegram` window

**Expected behavior**

window b got maximized

**Actual behavior**

size of window b do not change

a gif would be large, if you want to see I will make one

**Comment by TimUntersberger** [comment]
@ramirezmike maybe we should just handle minimized applications the same as closed applications to prevent this kind of problem?

I guess if a user manually minimzes the application this is the expected behaviour anyways?

**Comment by ramirezmike** [comment]
I thought about this a bit and.. treating a minimize the same as unmanaging would be the simplest way to handle it. 

An alternative to handle it is to track the layout of everything so that when you restore the window it pops back in where it was and everything returns to the size that it was... but that likely will introduce a bunch of weird edge cases to debate about.

My vote is to just treat minimize as if you're unmanaging the given window.

**Comment by TimUntersberger** [comment]
> My vote is to just treat minimize as if you're unmanaging the given window.

👍

**Comment by TimUntersberger** [comment]
Should be fixed in latest version.
